### ISSUE TITLE
page not loading with direct url but works fine with navigation

### ISSUE THREAD

**Issue by navdeepg2021** [source-cooperative/source.coop#19] opened 2024-11-05 16:34 UTC
pmtiles page rendering doesn't work using deeplinks but works if traverse to that page.

- https://source.coop/vida/google-microsoft-osm-open-buildings/pmtiles/goog_msft_osm_country_layers.pmtiles
- https://source.coop/vida/google-microsoft-osm-open-buildings/pmtiles/goog_msft_osm.pmtiles

On browsing these two pages directly, page doesnt load and stays in loading state but if you navigate to the pages, it loads just fine.

This is very common issue with any repository file which is available on browsing to the repository and is not limited to this particular page.

An example from local execution:
<img width="1132" alt="image" src="https://github.com/user-attachments/assets/fd6e17bc-177f-4aa6-b2b8-a40b08a62a26">

**Comment by kbgg** [comment] 2024-11-05 16:54
Duplicate of #14, closing.

**Closed by kbgg** 2024-11-05 16:54 UTC
